"""布局常量：窗口尺寸、控件大小、对话框尺寸、列表尺寸"""
DEFAULT_SW = 1360
DEFAULT_SH = 885
SW = DEFAULT_SW
SH = DEFAULT_SH
CPH = 100
MH = SH - CPH

HEMISPHERE_NORTH = "north"
HEMISPHERE_SOUTH = "south"

MODE_NORMAL = "normal"
MODE_SEASON = "season"
MODE_EDIT = "edit"

FADE_DURATION = 30.0
SEASON_SPEED_DEFAULT = 12 * 3600
MAX_INFO_BOX_SLOTS = 8

ICON_SET_SIMPLE = "simple"
ICON_SET_SMCY = "smcy"
ICON_SET_NAMES = {ICON_SET_SIMPLE: "简单图标", ICON_SET_SMCY: "SMCY图标"}
ICON_SET_DEFAULT = ICON_SET_SIMPLE

SUCAI_DIR = "./assets/"
SOUND_DIR = "./sound/"
MAP_DIR = "./map/"
TYPHOON_DIR = "./typhoon/"
CONFIG_FILE = "config.json"
USER_PREFS_FILE = "temp.json"
DEFAULT_MAP = "./map/map.png"
CUSTOM_MAP = "./map/custom_map.png"
LAND_MASK = "./map/land.png"
AREA_OCEAN_FILE = "./assets/Area_ocean.json"

DIALOG_TITLE_BAR_HEIGHT = 45
DIALOG_CORNER_RADIUS = 10
DIALOG_BG_ALPHA = 230
DIALOG_BORDER_WIDTH = 2

CONTROL_BUTTON_W = 80
CONTROL_BUTTON_H = 25
CONTROL_BUTTON_SPACING = 5
SPEED_BAR_W = 112
SPEED_BAR_H = 12
CONTROL_PANEL_ROW1_Y_OFFSET = 15
CONTROL_PANEL_ROW2_Y_OFFSET = 55

ACE_CHART_DEFAULT_WIDTH = 1800
ACE_CHART_DEFAULT_HEIGHT = 1200
ACE_CHART_PADDING_LEFT = 70
ACE_CHART_PADDING_RIGHT = 20
ACE_CHART_PADDING_TOP = 60
ACE_CHART_GRAPH_HEIGHT = 300

TY_LIST_ROWS_PER_PAGE = 6
TY_LIST_ITEM_HEIGHT = 70
TY_LIST_WIDTH = 650
TY_LIST_TOP_OFFSET = 60

POINT_LIST_ROWS_PER_PAGE = 15
POINT_LIST_WIDTH = 900
POINT_LIST_ROW_HEIGHT = 30
POINT_LIST_HEADER_Y = 45

INFO_BOX_WIDTH = 250
INFO_BOX_HEIGHT = 220
INFO_BOX_POS_X = 15
INFO_BOX_POS_Y = 15
SEASON_INFO_BOX_WIDTH = 350
SEASON_INFO_BOX_START_X = 15
SEASON_INFO_BOX_START_Y = 245
SEASON_INFO_BOXES_PER_COL = 8
SEASON_INFO_BOX_MAX_COLS = 1
SEASON_INFO_BOX_SPACING_X = 8
SEASON_INFO_BOX_SPACING_Y = 5

ACE_DISPLAY_BOX_WIDTH = 180
ACE_DISPLAY_BOX_HEIGHT = 80
ACE_DISPLAY_PROGRESS_HEIGHT = 20

TIME_JUMP_WIDTH = 400
TIME_JUMP_HEIGHT = 380

SETTINGS_WIDTH = 500
SETTINGS_HEIGHT = 620

DEFAULT_POINT_RADIUS = 3
PATH_LINE_WIDTH = 2
MAX_CIRCLE_CACHE = 256
INFO_BOX_CORNER_RADIUS = 10
SEASON_CLOCK_RADIUS = 40

FILE_FORMAT_SIMPLE_BDECK = "simple_bdeck"
FILE_FORMAT_JTWC = "jtwc"
FILE_FORMAT_AUTO = "auto"
